### PR TITLE
Add full docs from code workflow

### PR DESCRIPTION
**Pull request by andrewphilipsmith**

### CODE REVIEW

**Comment by andrewphilipsmith** [comment]
@James-Thompson-724 I have requested that readthedocs.io should be able to access this repo. Please review and approve if you agree. Happy to discuss if you wish.

**Comment by andrewphilipsmith** [comment]
@James-Thompson-724 
This is ready to review and merge.

It would be good to merge this now as it establishes `docs/source/user_guide.rst` as the source for truth for the user guide (replacing the previous `docs/user_guide.tex`)

However there are some things that are not included in this PR. Some additional improvements to the docs and the related workflow, which I've added to this issue https://github.com/PandemiaProject/pandemia/issues/74

**Comment by James-Thompson-724** [comment]
Looks good!

Taking, for example, the class `Region`, in the code I've written a docstring describing the 5 parameters, followed by individual docstring for each of the attributes. That leads to some repetition in the generated documentation (for the 5 parameters), so I guess I should simplify those docstrings?

**Review by James-Thompson-724 — APPROVED** [review]
Looks good!

Taking, for example, the class Region, in the code I've written a docstring describing the 5 parameters, followed by individual docstring for each of the attributes. That leads to some repetition in the generated documentation (for the 5 parameters), so I guess I should simplify those docstrings?

**Comment by andrewphilipsmith** [comment]
> Taking, for example, the class Region, in the code I've written a docstring describing the 5 parameters, followed by individual docstring for each of the attributes. That leads to some repetition in the generated documentation (for the 5 parameters), so I guess I should simplify those docstrings?

Yes - but hold fire for now! Have a look at the [napoleon extension](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html). This add supports for either NumPy or Google style Docstring (a subjective, aesthetic choice, but one that needs to be consistent). Those styles guide how to describe parameters. There are also options for Type information to be automatically extracted so that you don't need to manually document that. I've added setting up napoleon to #74.

**Comment by James-Thompson-724** [comment]
Ok sounds good, I'll check out that extention

**Pull request merged**
