### PR TITLE
This adds initial builds for MacOS and Linux (not fully functional)

### PR DESCRIPTION
**Pull request by AoifeHughes**

### CODE REVIEW

**Comment by AoifeHughes** [comment]
Will merge once these criteria are all met:

Tested this on fresh installs of 

- [ ] MacOS
- [ ] Windows 11 

With `Python=3.10` 

Using the `readme.md` listed simulations:

- [ ] `pandemia Scenarios/Global/global_config.yaml`
- [ ] `pandemia Scenarios/Global_Grid/global_grid_config.yaml`
- [ ] `pandemia Scenarios/Global_Grid/global_grid_config.yaml Scenarios/Global_Grid/global_grid_world.wld`
- [ ] `pandemia Scenarios/Global_Grid/global_grid_config.yaml Scenarios/Global_Grid/global_grid_world.wld`

**Comment by AoifeHughes** [comment]
`pandemia Scenarios/Global_Grid/global_grid_config.yaml` is throwing some errors, need to resolve these before continuing

**Comment by AoifeHughes** [comment]
Hi @James-Thompson-724 would you mind running:
`pandemia Scenarios/Global_Grid/global_grid_config.yaml` 

Just to check it is working, for me it's being odd.

**Comment by James-Thompson-724** [comment]
Hi @AoifeHughes I've tried running this and the other scenarios on this branch, however, I get an error:
`ModuleNotFoundError: No module named 'pandemia.world.world'`
So in particular the Global_Grid scenario produces this error too

**Comment by AoifeHughes** [comment]
did you do a `git pull` to get more recent changes the error `ModuleNotFoundError: No module named 'pandemia.world.world'` was fixed a few commits ago? and are you installing with `pip install .` rather than `pip install -e .`

**Comment by James-Thompson-724** [comment]
Yep, that fixed it!

Also, I installed Chocolately etc with no issues, it builds the dlls without errors.

**Pull request merged**
