### PR TITLE
Default input model

### PR DESCRIPTION
**Pull request by AoifeHughes**
Do not merge until  e2e testing has been pulled into develop

### CODE REVIEW

**Comment by AoifeHughes** [comment]
@andrewphilipsmith I'm just handling this merge now. I see there's some changes to the `test_all_components.yaml` file. Some parameters mostly. Is this all still okay?

I'll continue with merging on the assumption that the newer commits are the correct ones. But can always revert if need be.

**Comment by AoifeHughes** [comment]
@James-Thompson-724 I noticed the tests fail here because `Scenarios/Global/data/country_data.csv` is missing. Are we removing a lot of these scenario files? If so, let me know what would be best. Im going to add back that one file for now, as it keeps the tests running!

**Comment by AoifeHughes** [comment]
See [11112a6](https://github.com/PandemiaProject/pandemia/pull/64/commits/11112a60560a585e0c7dcb293e70ea5e1bf796f9) for readding of Global scenarios

**Comment by James-Thompson-724** [comment]
The test config test_global_config.yaml references `Scenarios/Global/data/country_data.csv`, and some other files inside `Global`, but this folder now should be called `Homogeneous`, so I think that may be the problem

**Pull request closed without merging**
