### PR TITLE
Feature/initial e2e testing

### PR DESCRIPTION
**Pull request by AoifeHughes**
PR for https://github.com/PandemiaProject/pandemia/issues/12

### CODE REVIEW

**Review by James-Thompson-724 — COMMENTED** [review]
Looks good! A couple of thoughts:
- Where the tick length is 600 (10 mins), perhaps we could increase it, for example to 28800 (8 hours), to speed up the tests?
- Perhaps the block of arrays initialized inside VectorRegion could instead be initialized inside the vectorize_component methods of the void models? Conceptually, the regions shouldn't know anything about the components, so if it works there it might be better (as you've got commented out in the void health model).

**Comment by andrewphilipsmith** [comment]
Thanks, James. Sorry, I pressed the reviewer link before I was ready with this message.

Please could you check the following:
* whether or not the scenarios I've included cover the range of epidemiological circumstances that you want to model. Are the expected results in the repo plausible? Do we need to add/alter any of the scenarios? (note that for small changes, we can patch existing scenarios in the test code rather than creating entirely new ones). 
* Are the instructions in the Readme.MD for running the end-to-end tests correct and easy to follow?

As you've seen, I've made some changes to the constructors/initialisation of some of the components. For now, these are just in order to get the end-to-end tests to work - I don't think that the way I've done them is ideal. I'd like to look at this a bit more systematically in due course, which caters for both the assumptions made elsewhere in either simulator.py or in the other components and for verifying the config file.

I'll have a try varying the tick length and see how much that speeds things up.

**Comment by James-Thompson-724** [comment]
- In addition to `test_end_to_end_global` we might also want something like `test_end_to_end_global_grid`, so perhaps at some point we could add that?
- In the `documentation` branch, which I'm currently working on, I've introduced a slightly modified `global_config.yaml`, to simplify the health model for that particular scenario. So, this would have a different set of expected results, I guess.
- My original test scenario, on which for example `test_all_components.yaml` is based, was intentionally a bit contrived, so the expected output is, from an epidemiological point of view, a bit weird. However it's what I'd expect to see, given the input. The output `strain_counts_test_global_config.csv` is based on the more realistic global scenario, and is therefore much more plausible. The output of global grid should be even more plausible.
- The most complicated bit of the whole thing is the immune system model, so perhaps at some point we could introduce additional end to end tests varying the number of strains (`global_config.yaml` currently has only 1) and varying the number of immune layers (`global_config.yaml` in this branch currently has 2, labelled `0` and `1` in the dictionary of presets, while in the `documenation` branch I've simplified it to have only 1).
I'm just having a look at the instructions in the Readme.MD now

**Comment by James-Thompson-724** [comment]
image
I do get a memory error when running `tests\test_end_to_end_pandimia.py` though

**Comment by AoifeHughes** [comment]
Yes! I’ll look into this!

**Comment by andrewphilipsmith** [comment]
I am *reasonably* convinced that these tests are working as expected and should be merged into the `develop` branch. There are failures, but I believe that these reflect the state of the production code not the tests:

- Most concerningly `test_end_to_end_all_components` is randomly unreliable on Mac. I've just tried running it repeatedly on my machine - it passed on 15 out of 19 attempts and produced a memory error on the other 4 occasions.
- `test_e2e_hospitalization_and_death_model` seems to fail consistently on Windows (memory error) but works consistently on Mac/Linux
- `test_e2e_vaccination_model` seems to produce different results depending on whether it is run on Windows or Mac/Linux, but behaves consistently on each platform.

Also, for the two tests which use approximate matching (`test_end_to_end_all_components` and `test_e2e_testing_and_contact_tracing_model`), the acceptable margins are very large (either +/- 100 absolute values, or +/- 50% relative values). These margins feel too big for the purpose of validating the results but were fine for the purpose of establishing the tests. They are easily changed.

I'll write up each of these points as separate Github Issues tomorrow.

**Pull request merged**
